//! The packaged APRS station icons, and the texture cache that draws them.
//!
//! Generated by `tools/gen_aprs_icons.py` — the drawings live there, in a 0..1
//! coordinate box, and the table below is written from
//! [`AprsSymbolKind`]'s own variant list. Edit the script and re-run it rather
//! than editing this file.
//!
//! They are compiled in rather than fetched, for the reason the country flags
//! are: a map that only shows what stations *are* once some third party's CDN
//! answers is a map that looks different on every machine, and the browser
//! client has no business reaching past sdroxide for one. Drawn rather than
//! sourced, so there is no third-party artwork in the tree.
//!
//! White on transparent, so the caller supplies the colour — the map fades a
//! station's icon as it ages, and colours our own station differently.

use std::collections::HashMap;

use eframe::egui;
use sdroxide_types::AprsSymbolKind;

/// One 48x48 image per symbol kind, in the enum's own order.
static ICON_PNG: &[(AprsSymbolKind, &[u8])] = &[
    (AprsSymbolKind::Unknown, include_bytes!("../assets/aprs/Unknown.png")),
    (AprsSymbolKind::Dot, include_bytes!("../assets/aprs/Dot.png")),
    (AprsSymbolKind::Circle, include_bytes!("../assets/aprs/Circle.png")),
    (AprsSymbolKind::Box, include_bytes!("../assets/aprs/Box.png")),
    (AprsSymbolKind::Star, include_bytes!("../assets/aprs/Star.png")),
    (AprsSymbolKind::Triangle, include_bytes!("../assets/aprs/Triangle.png")),
    (AprsSymbolKind::X, include_bytes!("../assets/aprs/X.png")),
    (AprsSymbolKind::House, include_bytes!("../assets/aprs/House.png")),
    (AprsSymbolKind::Hospital, include_bytes!("../assets/aprs/Hospital.png")),
    (AprsSymbolKind::School, include_bytes!("../assets/aprs/School.png")),
    (AprsSymbolKind::Restaurant, include_bytes!("../assets/aprs/Restaurant.png")),
    (AprsSymbolKind::Church, include_bytes!("../assets/aprs/Church.png")),
    (AprsSymbolKind::Parking, include_bytes!("../assets/aprs/Parking.png")),
    (AprsSymbolKind::Campground, include_bytes!("../assets/aprs/Campground.png")),
    (AprsSymbolKind::Shelter, include_bytes!("../assets/aprs/Shelter.png")),
    (AprsSymbolKind::Lighthouse, include_bytes!("../assets/aprs/Lighthouse.png")),
    (AprsSymbolKind::Firehouse, include_bytes!("../assets/aprs/Firehouse.png")),
    (AprsSymbolKind::PoliceStation, include_bytes!("../assets/aprs/PoliceStation.png")),
    (AprsSymbolKind::Digipeater, include_bytes!("../assets/aprs/Digipeater.png")),
    (AprsSymbolKind::Igate, include_bytes!("../assets/aprs/Igate.png")),
    (AprsSymbolKind::Node, include_bytes!("../assets/aprs/Node.png")),
    (AprsSymbolKind::Antenna, include_bytes!("../assets/aprs/Antenna.png")),
    (AprsSymbolKind::Yagi, include_bytes!("../assets/aprs/Yagi.png")),
    (AprsSymbolKind::Dish, include_bytes!("../assets/aprs/Dish.png")),
    (AprsSymbolKind::Server, include_bytes!("../assets/aprs/Server.png")),
    (AprsSymbolKind::Computer, include_bytes!("../assets/aprs/Computer.png")),
    (AprsSymbolKind::Phone, include_bytes!("../assets/aprs/Phone.png")),
    (AprsSymbolKind::Car, include_bytes!("../assets/aprs/Car.png")),
    (AprsSymbolKind::Truck, include_bytes!("../assets/aprs/Truck.png")),
    (AprsSymbolKind::Van, include_bytes!("../assets/aprs/Van.png")),
    (AprsSymbolKind::Bus, include_bytes!("../assets/aprs/Bus.png")),
    (AprsSymbolKind::Motorcycle, include_bytes!("../assets/aprs/Motorcycle.png")),
    (AprsSymbolKind::Bicycle, include_bytes!("../assets/aprs/Bicycle.png")),
    (AprsSymbolKind::Rv, include_bytes!("../assets/aprs/Rv.png")),
    (AprsSymbolKind::Train, include_bytes!("../assets/aprs/Train.png")),
    (AprsSymbolKind::Ambulance, include_bytes!("../assets/aprs/Ambulance.png")),
    (AprsSymbolKind::FireTruck, include_bytes!("../assets/aprs/FireTruck.png")),
    (AprsSymbolKind::Police, include_bytes!("../assets/aprs/Police.png")),
    (AprsSymbolKind::Tractor, include_bytes!("../assets/aprs/Tractor.png")),
    (AprsSymbolKind::Aircraft, include_bytes!("../assets/aprs/Aircraft.png")),
    (AprsSymbolKind::AircraftLarge, include_bytes!("../assets/aprs/AircraftLarge.png")),
    (AprsSymbolKind::Helicopter, include_bytes!("../assets/aprs/Helicopter.png")),
    (AprsSymbolKind::Balloon, include_bytes!("../assets/aprs/Balloon.png")),
    (AprsSymbolKind::Glider, include_bytes!("../assets/aprs/Glider.png")),
    (AprsSymbolKind::Rocket, include_bytes!("../assets/aprs/Rocket.png")),
    (AprsSymbolKind::Satellite, include_bytes!("../assets/aprs/Satellite.png")),
    (AprsSymbolKind::Boat, include_bytes!("../assets/aprs/Boat.png")),
    (AprsSymbolKind::Yacht, include_bytes!("../assets/aprs/Yacht.png")),
    (AprsSymbolKind::Person, include_bytes!("../assets/aprs/Person.png")),
    (AprsSymbolKind::Emergency, include_bytes!("../assets/aprs/Emergency.png")),
    (AprsSymbolKind::RedCross, include_bytes!("../assets/aprs/RedCross.png")),
    (AprsSymbolKind::Fire, include_bytes!("../assets/aprs/Fire.png")),
    (AprsSymbolKind::Eyeball, include_bytes!("../assets/aprs/Eyeball.png")),
    (AprsSymbolKind::WxStation, include_bytes!("../assets/aprs/WxStation.png")),
    (AprsSymbolKind::Rain, include_bytes!("../assets/aprs/Rain.png")),
    (AprsSymbolKind::Snow, include_bytes!("../assets/aprs/Snow.png")),
    (AprsSymbolKind::Thunderstorm, include_bytes!("../assets/aprs/Thunderstorm.png")),
    (AprsSymbolKind::Hurricane, include_bytes!("../assets/aprs/Hurricane.png")),
    (AprsSymbolKind::Tornado, include_bytes!("../assets/aprs/Tornado.png")),
    (AprsSymbolKind::Cloudy, include_bytes!("../assets/aprs/Cloudy.png")),
    (AprsSymbolKind::Sunny, include_bytes!("../assets/aprs/Sunny.png")),
];

/// Lazily decoded icon textures, one per kind.
#[derive(Default)]
pub struct AprsIcons {
    tex: HashMap<AprsSymbolKind, egui::TextureHandle>,
}

impl AprsIcons {
    /// The texture for `kind`, decoding it the first time it is asked for.
    ///
    /// `None` only if the PNG will not decode, which would be a build problem
    /// rather than a runtime one — the caller draws a plain dot instead, so a
    /// station is never invisible for want of a picture.
    pub fn get(
        &mut self,
        ctx: &egui::Context,
        kind: AprsSymbolKind,
    ) -> Option<&egui::TextureHandle> {
        if !self.tex.contains_key(&kind) {
            let bytes = ICON_PNG.iter().find(|(k, _)| *k == kind).map(|(_, b)| *b)?;
            let img = image::load_from_memory(bytes).ok()?.to_rgba8();
            let (w, h) = img.dimensions();
            let colour =
                egui::ColorImage::from_rgba_unmultiplied([w as usize, h as usize], img.as_raw());
            let handle = ctx.load_texture(
                format!("aprs-icon-{kind:?}"),
                colour,
                egui::TextureOptions::LINEAR,
            );
            self.tex.insert(kind, handle);
        }
        self.tex.get(&kind)
    }

    /// Draw `kind` centred in `rect`, tinted `tint`.
    ///
    /// Falls back to a filled dot where the texture is missing: a station with
    /// no icon still has to be on the map.
    pub fn paint(
        &mut self,
        ui: &egui::Ui,
        rect: egui::Rect,
        kind: AprsSymbolKind,
        tint: egui::Color32,
    ) {
        let uv = egui::Rect::from_min_max(egui::pos2(0.0, 0.0), egui::pos2(1.0, 1.0));
        match self.get(ui.ctx(), kind) {
            Some(t) => {
                ui.painter().image(t.id(), rect, uv, tint);
            }
            None => {
                ui.painter().circle_filled(rect.center(), rect.width() * 0.25, tint);
            }
        }
    }
}
